apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

configurations:
  - envsubst-config.yaml

configMapGenerator:
  - name: velero-values
    envs:
      - .env

generatorOptions:
  disableNameSuffixHash: true
