name: eks-automation
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-22.04
    steps:
      - name: first-step
        run: |
            echo "First line of multi line"
            echo "Second line of multi line"
      - name: second-step
        run: echo "Can we start ?"